### ISSUE TITLE
Not allowing images from S3

### ISSUE THREAD

**Issue by Ryan8765** [piotrzdziarski/fslightbox-react#89]
For some reason - when trying to pull images from S3 - I am getting "invalid file" for any image.  Example image to test:

https://escalante-mkt-imgs.s3-us-west-2.amazonaws.com/TimeSheets/screenshot1.png

**Comment by piotrzdziarski** [comment]
If you will set disableLocalStorage prop to **true** you will see error in console:
![image](https://user-images.githubusercontent.com/38288006/59151970-ed45f800-8a3b-11e9-9f93-80f00c558328.png)

That means that lightbox cannot check type automatically due to CORS policy.
If enabling CORS in S3 is possible you can fix this by doing it.

On the other hand I think I will make an update that adds manual type declaration. This will be better solution for this case.

**Comment by Ryan8765** [comment]
The odd thing is this is a public S3 bucket.  I am already loading it via an image elements src attribute.

**Comment by Ryan8765** [comment]
> If you will set disableLocalStorage prop to **true** you will see error in console:
> ![image](https://user-images.githubusercontent.com/38288006/59151970-ed45f800-8a3b-11e9-9f93-80f00c558328.png)
> 
> That means that lightbox cannot check type automatically due to CORS policy.
> If enabling CORS in S3 is possible you can fix this by doing it.
> 
> On the other hand I think I will make an update that adds manual type declaration. This will be better solution for this case.

Thanks!

**Comment by piotrzdziarski** [comment]
New version is available. Now you can set types manually by passing an array with types to new **types** prop. Three types are available: 
- 'image'
- 'video'
- 'youtube'

Example at: [https://fslightbox.com/react/documentation#prop-types](https://fslightbox.com/react/documentation#prop-types )
Enjoy!
